version: "3.9"

networks:
  my_server:
    driver: bridge

services:
  server_project:
    build:
      context: ./server_project
    command: >
      sh -c "python manage.py makemigrations &&
            python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/server_project
    networks:
      - my_server

  elasticsearch:
    image: elasticsearch:7.14.0
    volumes:
      - ./data/elastic:/var/lib/elasticsearch/data
    environment:
      - discovery.type=single_node
    ports:
      - 9200:9200
    networks:
      - my_server