version: "3.9"

networks:
  my_server:
    driver: bridge

# volumes:
#   certs:
#     driver: local
#   es_data:
#     driver: local

services:
  server_project:
    build:
      context: ./server_project
    # command: >
    #   sh -c "python manage.py makemigrations &&
    #         python manage.py migrate &&
    #         python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./server_project:/server_project
    ports:
      - "8000:8000"
    depends_on:
      - es
    networks:
      - my_server

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.3
    environment:
      - node.name=es
      - discovery.type=single-node # single-node 로 만든다.
      - discovery.seed_hosts=es
      - ELASTIC_PASSWORD=ecubelabs
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.http.ssl.verification_mode=certificate
      - xpack.security.transport.ssl.enabled=false
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.license.self_generated.type=basic
    mem_limit: 1073741824
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s --cacert config/certs/ca/ca.crt http://localhost:9200 | grep -q 'missing authentication credentials'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120
    volumes:
      - ./server_project/es_data:/usr/share/es/data
      - ./server_project/certs:/usr/share/elasticsearch/config/certs
    ports:
      - 9200:9200
    networks:
      - my_server

  kibana:
    image: docker.elastic.co/kibana/kibana:8.4.3
    environment:
      - ELASTICSEARCH_HOSTS=http://es:9200
    ports:
      - 5601:5601
    depends_on:
      - es
    networks:
      - my_server