version: "3.9"

networks:
  my_server:
    driver: bridge

services:
  server_project:
    build:
      context: ./server_project
    # command: >
    #   sh -c "python manage.py makemigrations &&
    #         python manage.py migrate &&
    #         python manage.py runserver 0.0.0.0:8000"
    # volumes:
    #   - ./server_project:/server_project
    ports:
      - "8000:8000"
    depends_on:
      - elasticsearch
    networks:
      - my_server

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    volumes:
      - ./server_project/data/elastic:/var/lib/elasticsearch/data
    environment:
      - discovery.type=single_node
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - my_server